### ISSUE TITLE
Обсуждение правок в моих правках

### ISSUE THREAD

**Issue by PROPHESSOR** [Nemrtvi/gzdoom-russian-translation#2]
https://github.com/SashaTheRed/gzdoom-russian-translation/blob/3829df38ce4c4ec00233c0ee4cb98835f023e5a1/pk3/language.rus#L321
На сколько я знаю, слово "Ад" пишется в русской версии с большой буквы (в думовской тематике)

https://github.com/SashaTheRed/gzdoom-russian-translation/blob/3829df38ce4c4ec00233c0ee4cb98835f023e5a1/pk3/language.rus#L1673
"НОЧНОЙ КОШМАР" звучит зловещее и больше подходит по смыслу. Если в данном месте нет ограничений на количество символов, предлагаю использовать именно его

https://github.com/SashaTheRed/gzdoom-russian-translation/blob/3829df38ce4c4ec00233c0ee4cb98835f023e5a1/pk3/language.rus#L1859
https://github.com/SashaTheRed/gzdoom-russian-translation/blob/3829df38ce4c4ec00233c0ee4cb98835f023e5a1/pk3/language.rus#L1860
https://github.com/SashaTheRed/gzdoom-russian-translation/blob/3829df38ce4c4ec00233c0ee4cb98835f023e5a1/pk3/language.rus#L1865
Там что, есть ограничения по количеству символов?

https://github.com/SashaTheRed/gzdoom-russian-translation/blob/3829df38ce4c4ec00233c0ee4cb98835f023e5a1/pk3/language.rus#L2326
Тогда уже "Предсказание действий **на** уровне"

**Comment by SashaTheRed** [comment]
> На сколько я знаю, слово "Ад" пишется в русской версии с большой буквы (в думовской тематике)

Хм, я не совсем уверен. В Google можно найти разнличные источники, а каждый имеет свой вариант. https://www.google.com/search?client=firefox-b-ab&q=%22%D0%B1%D0%B5%D1%80%D0%B5%D0%B3%D0%B0+%D0%B0%D0%B4%D0%B0%22

Думаю, что изменю в любом случае.

> "НОЧНОЙ КОШМАР" звучит зловещее и больше подходит по смыслу. Если в данном месте нет ограничений на количество символов, предлагаю использовать именно его

Я подумал об этом названии и пришёи к такому выводу: «Ночь» в игре вообще ни при чём, и «Кошмар» вполне себе самостоятельное слово. Ещё пример: «Мне приснился кошмар», а не «Мне приснился ночной кошмар».

Также в PSX Doom есть разновидность пинки, которая называется «Nightmare Spectre». Он теперь должен стать «Призраком ночного кошмара»?

Кроме того, при изменении названия также нужно будет переделать графику. Поэтому, если оно когда-либо заменится, заменится поздно в цикле разработки.

> Там что, есть ограничения по количеству символов?

В некотором роде, да. С данными изменениями меню выглядит [так](http://u.cubeupload.com/SashaRed/nastrojki.png). Слайдеры не располагаются корректно, и текст «автоприцеливание» сталкивается с просмотром игрока.

> Тогда уже "Предсказание действий **на** уровне"

Поправлено. Благодарю.

**Comment by PROPHESSOR** [comment]
> «Ночь» в игре вообще ни при чём, и «Кошмар» вполне себе самостоятельное слово. Ещё пример: «Мне приснился кошмар», а не «Мне приснился ночной кошмар».

"Кошмар" в данном случае означает эмоциональное состояние, а "Ночной кошмар" конкретный, простите за слово, предмет. В данном случае, уровень сложности представляет из себя ночной кошмар, ибо, если уже сокращать до одного слова, то получится "Кошмарный"... А это звучит не очень

> Также в PSX Doom есть разновидность пинки, которая называется «Nightmare Spectre». Он теперь должен стать «Призраком ночного кошмара»?
Как не странно, этот перевод звучит вполне логично

> В некотором роде, да. С полным текстом, меню будет выглядеть так. Слайдеры не располагаются корректно, и текст «автоприцеливание» сталкивается с просмотром игрока.
Хорошо, вопрос закрыт (такие места лучше пометить комментариями в переводе)

> На этой ноте, нужно придумать текст получше для строки «Switch on pickup»
Если честно, не понял... Слово "нота" подразумевает ноту в музыке... Логичнее по смыслу (если я правильно понял, в чём я сомневаюсь) подходит "В этом случае" (In this case)

**Comment by SashaTheRed** [comment]
В общем, большинство изменений принято.

Но прежде чем продолжать переделать больше названий, я хотел бы разобраться с остальными проблемами в переводе. Я, разумеется, не хочу зря заменить изображения уровней.

А пока лучше хранить все предложенные названия в одном посте. Вот те, что были в pull request-е.

```
HUSTR_E4M1 = "E4M1: Над Преисподней";
HUSTR_E4M2 = "E4M2: Истинная Ненависть";
HUSTR_E4M3 = "E4M3: Истязание нечестивых";

HUSTR_E4M6 = "E4M6: Супротив сих нечестивых";
```

---

При чём в файле строки 2551—2566? Их не существует в _language.enu_.

**Comment by PROPHESSOR** [comment]
> При чём в файле строки 2551—2566? Их нет в language.enu.

Возможно, они там были в прошлых версиях

> E4M6: Выступи Против Своих Пороков
> E4M7: И Последуй в Ад

Это откуда это такие переводы нарисовались?

**Comment by SashaTheRed** [comment]
> Это откуда это такие переводы нарисовались?

От переводчика большой игры, у которого я спросил совета.

**Comment by PROPHESSOR** [comment]
В общем, кроме 
> Вырви Нечестивцев
Звучит очень даже хорошо

**Comment by PROPHESSOR** [comment]
А на счёт второго эпизода - все же, предлагаю остановиться на варианте «Прибрежье Ада»
По [этой](https://github.com/SashaTheRed/gzdoom-russian-translation/commit/9f6b63eb9fb3edd525b999df8a52526e02accdb8#r31923141) причине и по общему звучанию

**Comment by SashaTheRed** [comment]
Я знаю. Лучше ставить все предложения по названиям в одном посте. Прямо сейчас не будут заменены.

**Comment by Nemrtvi** [comment]
С выпуском версии 4.0.0 GZDoom проект переделан во всех областях — теперь он больше не включает в себя сам перевод на русский язык, а только дополнительные материалы (например, строку состояния, экраны помощи и т.д.).

Поэтому закрою данную тему. Есть ряд других подходов, если дальше нужно будет сообщать о проблемах:

1. Присоединиться к [нашему русскоговорящему серверу в Discord](https://discord.gg/sKDcfVh), и зайти в канал _#russian_gzdoom_обсуждение_, чтобы рассказывать о всех обнаружениях, предложениях и мыслях
    - У нас часто проводятся обсуждения о переводе, и мы рады любой помощи
2. Заходить в [тему на форуме Doom Power](https://i.iddqd.ru/viewtopic.php?t=1492)
3. Заходить в [тему на форуме ZDoom](https://forum.zdoom.org/viewtopic.php?f=19&t=58872)
